# Generated by Django 5.2.7 on 2025-11-13 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_termsandconditions_usertermsacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThalerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thalers_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
