# Generated by Django 5.2.7 on 2025-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_thalertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
