# Generated by Django 5.2.7 on 2025-10-30 22:17

from django.db import migrations

def create_initial_achievements(apps, schema_editor):
    Achievement = apps.get_model('achievements', 'Achievement')
    achievements = [
        ("First Quiz!", "Complete your first quiz.", 50, "Finish your first quiz."),
        ("Quiz Explorer", "Complete 10 quizzes.", 200, "Finish 10 different quizzes."),
        ("Knowledge Seeker", "Reach 1000 total XP.", 300, "Accumulate 1000 XP."),
        ("Perfect Score", "Score 100% on a quiz.", 150, "Get 100% in any quiz."),
    ]
    for title, desc, xp, req in achievements:
        Achievement.objects.get_or_create(
            title=title,
            defaults={"description": desc, "xp_reward": xp, "requirement": req},
        )

class Migration(migrations.Migration):
    dependencies = [
        ('achievements', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_initial_achievements),
    ]