# Generated by Django 5.2.7 on 2025-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='xp_reward',
            field=models.IntegerField(default=0),
        ),
    ]
