# Generated by Django 5.2.7 on 2025-11-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_room_quiz_room_status_roomparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
