# Generated by Django 5.2.7 on 2025-11-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_alter_room_status_delete_roomparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
