# Generated by Django 5.2.7 on 2025-10-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_status_quizreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
