# Generated by Django 5.2.7 on 2025-11-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_is_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='xp_earned',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
