# Generated by Django 5.2.7 on 2025-11-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
